import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My-Blog</title>
        <meta name="description" content="Generated by create next app Mybolg" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/about" passHref >About</Link>
    </div>
  )
}
